# Generated by Django 4.2.13 on 2024-05-27 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
